export const MOCKUP_CATEGORIES: string[] = [
  'Camiseta',
  'Moletom',
  'Boné',
  'Papelaria',
  'Fachada de Loja',
  'Embalagem',
  'Caixa de Produto',
  'Caneca',
  'Celular',
  'Smartwatch',
  'Desktop',
  'Laptop',
  'Tablet',
  'Tela de TV',
  'Mural',
  'Sacola de Compras',
  'Cartão de Visita',
  'Livro',
  'Pôster',
  'Flyer',
  'Outdoor',
  'Redes Sociais',
  'Garrafa',
  'Rótulo de Vinho',
  'Lata de Bebida',
  'Almofada',
  'Capa de Celular',
  'Skate',
  'Prato',
  'Banner Roll-up',
  'Menu de Restaurante',
  'Caderno',
  'Calendário',
  'Totem',
  'Meias',
  'Sacola de tecido (Tote Bag)',
  'Capa de E-reader',
  'Pote de Cosmético',
  'Garrafa de Cerveja',
  'Capa de Disco de Vinil',
  'Anúncio em Metrô',
  'Cartão de Crédito',
  'Bandeira',
  'Mousepad',
  'Quebra-cabeça',
  'Ímã de Geladeira',
  'Rótulo de Suplemento',
  'Caixa de Pizza',
  'Guardanapo',
  'Jogo Americano',
  'App em Smart TV',
  'Embalagem de Comida (Saco)',
  'Crachá',
  'Caneta',
  'Isqueiro',
];

export const LAYOUT_PRESETS: string[] = [
  'Vista de frente, centralizado',
  'Close-up no detalhe',
  'Ângulo isométrico',
  'Cena de lifestyle (com pessoas)',
  'Flat lay (vista de cima)',
  'Em uma prateleira ou display',
  'Perspectiva angular',
  'Ambiente de escritório',
  'Em mãos de uma pessoa',
  'Flutuando com fundo neutro',
  'Cena de unboxing',
  'Composição com objetos relacionados',
  'Em um display de loja',
  'Ângulo de contra-plongée (de baixo para cima)',
  'Vista de plongée (de cima para baixo)',
  'Detalhe em macro',
  'Em ambiente de trabalho (mesa de escritório)',
  'Sendo usado em um contexto real',
  'Fundo desfocado (bokeh)',
  'Múltiplas unidades em um padrão',
  'Dentro de uma mochila ou bolsa',
  'Em uma vitrine',
  'Composição criativa com elementos gráficos',
];

export const STYLE_PRESETS: string[] = [
  'Minimalista e limpo',
  'Estúdio com iluminação profissional',
  'Ambiente externo, luz natural',
  'Colorido e vibrante',
  'Escuro e dramático',
  'Cyberpunk com luzes neon',
  'Aconchegante e quente (Hygge)',
  'Luxuoso com detalhes em ouro',
  'Brutalista com fundo de concreto',
  'Sonhador e surreal',
  'Estética retrô anos 80',
  'Sci-fi futurista',
  'Gótico e sombrio',
  'Tropical com folhagens',
  'Industrial com metal e tijolo',
  'Boho chic com elementos naturais',
  'Art Déco com formas geométricas',
  'Steampunk com engrenagens e cobre',
  'Pastel suave e delicado',
  'Grunge com texturas gastas',
  'Pop Art super colorido',
  'Fantasia com atmosfera mágica',
  'Aquático com reflexos de água',
  'Desértico com areia e luz forte',
  'Urbano com graffiti e elementos de rua',
];

export const MAX_HISTORY_SIZE = 40;
